### ISSUE TITLE
support for comment block

### ISSUE THREAD

**Issue by tungv** [ionut-botizan/vscode-cypher-ql#1]
Hi,
I think there is a good use of block comment to mark a string is in cypher grammar.

for example:

```js
function example() {
  return /* cypher */` MATCH (n) RETURN n`
}
```

vscode-graphql supports this:
https://github.com/prisma/vscode-graphql/blob/master/grammars/graphql.js.json

if you don't have time, I can try it myself and create a PR.
Thanks

**Comment by ionut-botizan** [comment]
Hi,

I'm sorry it took this long to answer, but I was very busy at the time you opened this pull request and then I completely forgot about it...
Anyway, thank you for contributing to this extension. I'll merge your changes and publish an update this week (I might add a couple of tweaks myself before updating it 🙂).

Best Regards,
Ionuț

**Comment by tungv** [comment]
thanks, looking forward to your updates
